services:
  web:
    #берем докерфайл для билда из текущей директории
    build: .
    #команда запуска контейнера на основе образа
    command: uvicorn main:app --host 0.0.0.0
    #куда перемещаются файлы из локальной папки
    volumes:
      - .:/app
    ports:
      - 5000:8000